<?php
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\ContentEntityInterface;

/**
 * Implements hook_entity_access.
 */
function port_core_entity_access(EntityInterface $entity, $operation, AccountInterface $account) {
  // Get the current user's "User" object
  $user = \Drupal::currentUser();

  // Check for permission
  if ($user->hasPermission('bypass password protection')) {
    return AccessResult::neutral();
  }

  if ($entity instanceof ContentEntityInterface) {
    $has_field_password = $entity->hasField('field_password');
    if ($has_field_password) {
      $field_password_is_empty = $entity->get('field_password')->isEmpty();
      if (!$field_password_is_empty) {
        if ($operation == 'view') {
          $password = $entity->get('field_password')->value;
          $url_token = $_GET['privateToken'];
          if ($url_token != $password) {
            return AccessResult::forbidden();
          }
        }
      }
    }
  }
  return AccessResult::neutral();
}

/**
 * Implements hook_form_alter.
 */
function port_core_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (!empty($form['field_password'])) {
    $config = \Drupal::config('port_core.password_settings');
    $password_option = $config->get('password_options');
    if ($password_option == 'list') {
      $password_options = $config->get('available_passwords');
      $options = explode("\n", $password_options);
      $options[''] = '- No password -';
      $form['field_password']['widget'][0]['value'] = [
        '#title' => 'Select a password',
        '#type' => 'select',
        '#default_value' => NULL,
        '#options' => $options
      ];
    }
  }
}
